version: '3.9'

services:

  postgres:
    image: postgres:15.5-alpine
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ~/apps/challenge_db_test:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=challenge
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 20s
      retries: 5

#   challenge:
#     build:
#       dockerfile: Dockerfile
#     env_file: .env
#     ports:
#       - "${PORT}:${PORT}"
#     expose:
#       - "${PORT}"
#     depends_on:
#       postgres:
#         condition: service_healthy
